### PR TITLE
Aurelie

### PR DESCRIPTION
**Pull request by Aurelie-Mutschler**
related to issue #35

### CODE REVIEW

**Comment by Aurelie-Mutschler** [comment]
Wait before merging - I have to update getstarted/hacking_guide.md

**Comment by benchoufi** [comment]
yes

**Comment by benchoufi** [comment]
done

**Comment by Aurelie-Mutschler** [comment]
What is done? :D

**Comment by benchoufi** [comment]
sorry typo ;) done was related to this : https://github.com/echopen/echopen_prototyping/issues/48

**Pull request merged**
