### PR TITLE
Adding mechanical component in the assembly guide 

### PR DESCRIPTION
**Pull request by kelu124**
Steps to #3 :
* complete the mechanical part + update some images 
* debug : images are not displayed in the gitbook (normally fixed - path are changed to absolute path, github-independant)

### CODE REVIEW

**Comment by kelu124** [comment]
A commit adding the issue #4 on image quality is added. Basically, articles reviewed yielded an interesting article for us. Image quality characterization would be done at first in two steps:
* Resolution of the probe at different levels and angles
* Using custom metrics for gray-scale ultrasound probe characterization.
@soobash don't hesitate to check the doc!

**Comment by Aurelie-Mutschler** [comment]
thanks a lot @kelu124 :)

The literature review seems really great! I think we should put it in the References/ section that is meant to highlight that kind of contribution, such that it will remain visible (and people could even refine it). What do you think?

**Comment by kelu124** [comment]
Tbh there is only one document so far that is really relevant for us, so why not.
The best way to store references would be to store bibtex or DOIs, that can be integrated afterwards depending on the structure we need :)

As you know, I'm a big fan of scripting documentation (because I'm purely lazy) - the default option I would suggest is to push bibtex items in the bio folder, with a script generating the bibliography file properly.

**Comment by Aurelie-Mutschler** [comment]
What do you mean by "bio folder" ?

The idea of using bibtex + a script to generate a bibliography is great, I'll add it to our project board ;-) 

But what you did is more than a bibliography, there are useful comments and so on so I think in this case we should include the whole file. Let's include it and see how we can automatize the sharing of references ?

**Comment by kelu124** [comment]
Okay, in this case I'll just put the bibliography in a separate file, leave the shortened review, and amend the request accordingly.

**Comment by kelu124** [comment]
Bibliography has been split now.

**Comment by Aurelie-Mutschler** [comment]
thanks ;)

**Comment by Aurelie-Mutschler** [comment]
@kelu124 the .md files for the bibliography don't appear in the gitbook, is that normal?

**Pull request merged**
