### PR TITLE
document Mobile app 4.0  

### PR DESCRIPTION
**Pull request by clecoued**

### CODE REVIEW

**Comment by clecoued** [comment]
@Aurelie-Mutschler to review

**Review by Aurelie-Mutschler — COMMENTED** [review]
@clecoued is there a way we get cleaner schemes?

**Comment by clecoued** [comment]
I try to improve the sketchs, not sure it's better ;(

**Comment by clecoued** [comment]
sketches has been updated @Aurelie-Mutschler

**Comment by Aurelie-Mutschler** [comment]
thanks @clecoued that's beautiful 😍 👏

**Pull request merged**
